name: Repository Dispatch Sample

on:
  repository_dispatch:
    types: [echo_message]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event is '${{ github.event.action }}'" 
          echo "Message is '${{ github.event.client_payload.message }}'"
