# This is a basic workflow to help you get started with Actions

name: reused CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    inputs:
      friend_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: false
    outputs:
      greeting_message:
        value: ${{ jobs.greeting.outputs.message }}
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greeting:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.message.outputs.message }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - id: message
        run: |
          echo "message=Hello ${{ inputs.friend_name }}" >> $GITHUB_OUTPUT
